# Generated by Django 2.0.2 on 2018-02-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='app_user',
            field=models.CharField(default='', max_length=200),
        ),
    ]
