# Generated by Django 2.0.2 on 2018-02-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_user', models.CharField(max_length=200)),
                ('article_link', models.CharField(max_length=300)),
            ],
        ),
    ]
