# Generated by Django 2.0.2 on 2018-02-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_savearticles'),
    ]

    operations = [
        migrations.AddField(
            model_name='savearticles',
            name='article_title',
            field=models.CharField(default='', max_length=300),
        ),
    ]
